data_config:
  dataset: 1128
  target: Tissue
  random_states:
    - 15
    - 108
    - 180
    - 234
    - 250
  task_type: binary
  na_threshold: 0.15
fit_config:
  dataset: 1128
  num_epochs: 512
  learning_rate: 1.0e-05
  task_type: binary
  project_name: tgrl_multi_modal
  random_state:
    - 15
    - 108
    - 180
    - 234
    - 250
  batch_size: 224
  batch_size_transform: 10000
  consistency: true
  multimodal: true
  verbose: true
  best_model_path: models/best_model.pth
  lr_patience: 10
  alpha: 0.2
  early_stopping_patience: 15
  consistency_loss_type: clip
